WCS\CoavBundle\Entity\Reservation:
    type: entity
    table: null
    repositoryClass: WCS\CoavBundle\Repository\ReservationRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        nbSeats:
            type:
    manyToMany:
        passengers:
            targetEntity: User
            mappedBy: reservation
    manyToOne:
        departure:
            targetEntity: WCS\CoavBundle\Entity\Flight
            inversedBy: departures
    lifecycleCallbacks: {  }
